# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA configuration cache
org.gradle.configuration-cache=false

# Fabric Properties
loom_version=1.15.5
minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.157.0+26.2

# Mod Properties
version=1.0.0
group=com.krimx.gamefixes

org.gradle.java.home=/usr/lib/jvm/java-25-openjdk-amd64